# ──────────────────────────────────────────────────────────────
#  General Rules
# ──────────────────────────────────────────────────────────────

windowrule = tile on, match:title ^(Neovide)$
windowrule = float on, match:title ^(Settings)$

windowrule = float on, match:title ^(Extension: \(Bitwarden Password Manager\) - Bitwarden - Zen Browser)$
windowrule = float on, match:title ^(Extension:.*Bitwarden.*)$, match:class ^(zen-alpha)$

windowrule = stay_focused on, match:title ^()$, match:class ^(steam)$
windowrule = min_size 1 1, match:title ^()$, match:class ^(steam)$


# ──────────────────────────────────────────────────────────────
#  Picture-in-Picture
# ──────────────────────────────────────────────────────────────

windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = size 320 180, match:title ^(Picture-in-Picture)$
windowrule = move 100%-325 100%-185, match:title ^(Picture-in-Picture)$
windowrule = no_initial_focus on, match:title ^(Picture-in-Picture)$
windowrule = tag -hyprbars:nobar, match:title ^(Picture-in-Picture)$
