# /home/wixaxis/.config/tmuxinator/default.yml

name: default
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f log/development.log
