# /home/wixaxis/.config/tmuxinator/default.yml

name: default
root: ~/
windows:
  - main_terminal: neofetch
  - files: yazi
  - auxiliary_terminal: neofetch
  - ollama:
    layout: main-horizontal
    panes:
      - "ollama run llama3.2"
      - "ollama serve"
  - updates: just update
