BASH_CONFIG_DIR="$HOME/.config/bash"

# DEBUG=true

_is_valid_bash_module() { [[ -f "$1" && "$1" == *.bash && -r "$1" ]] }

_debug_echo() { [ "$DEBUG" == "true" ] && echo "$1"; }

_source_all_recursively() {                     # Source all bash modules in directory recursively
    if [ -d "$1" ]; then                          # Check if the passed dir is a valid directory
        for entry in "$1"/*; do                     # For each entry in the directory
            if _is_valid_bash_module "$entry"; then   # IF entry is a valid bash module file
                _debug_echo "Sourcing $entry"           # DEBUG: output the sourced file
                source "$entry"                         # Source the file
            elif [ -d "$entry" ]; then                # ELSE IF entry is a directory
              _debug_echo "Recursing -> $entry"         # DEBUG: output
              _source_all_recursively "$entry"          # Recurse into subdirectory
            fi
        done
    fi
}

_source_all_recursively "$BASH_CONFIG_DIR/modules"
